### ISSUE TITLE
contact name auto fill doesn't work when surname is blank

### ISSUE THREAD

**Issue by jumshudsultan** [ERPGO/odoo-insurance-az#35]
When customer_surname field in res.partner is blank def create function doesn't work (adding name surname and pin code)

**Comment by jumshudsultan** [comment]
![image (3)](https://user-images.githubusercontent.com/43217182/73723086-a1ba2a00-4741-11ea-86a8-38b5f93cd222.png)

**Comment by nurlanf** [comment]
fixed in #38
