### ISSUE TITLE
Yalnış hesablanma. 

### ISSUE THREAD

**Issue by gulmemmedliorxan** [ERPGO/odoo-insurance-az#47]
Bonus regional parameters'de mueyyen meblegler arasinda hesablanmasi emri verilir, sistem bu meblegden cox olanlarida hesablayir. (Hetta bolge "baki" secilse bele, regiona da elave edir.)

**Comment by jumshudsultan** [comment]
@gulmemmedliorxan

**Comment by jumshudsultan** [comment]
eger yuxari range qoyulmayibsa sistem avtomatik mueyyenleshdirilmish en yuxari range'i ondan yuxari range'lara da shamil edir. Duzgun hesablayir.
