### ISSUE TITLE
Create date to payment date in basic sheet. 

### ISSUE THREAD

**Issue by gulmemmedliorxan** [ERPGO/odoo-insurance-az#51]
![image](https://user-images.githubusercontent.com/50625583/74228515-047b6a80-4cda-11ea-9f27-6e6e5ee3dda7.png)
Sales moduluna giren kimi acilan sehifede gorunen create date evezine odenis tarixi gorsensin.

**Comment by jumshudsultan** [comment]
@gulmemmedliorxan please check, it's fixed
